### ISSUE TITLE
Fill missing licenses, dependencies, and buildInputs (simple plugins)

### ISSUE THREAD

**Issue by m15a** [m15a/nixpkgs-vim-extra-plugins#17]
## TODO

- [x] [AckslD/nvim-revJ.lua](https://github.com/AckslD/nvim-revJ.lua) `nvim-revJ-lua`
- [x] [AllenDang/nvim-expand-expr](https://github.com/AllenDang/nvim-expand-expr) `nvim-expand-expr`
- [x] [CRAG666/code_runner.nvim](https://github.com/CRAG666/code_runner.nvim) `code-runner-nvim`
- [x] [David-Kunz/cmp-npm](https://github.com/David-Kunz/cmp-npm) `cmp-npm`
- [x] [David-Kunz/jester](https://github.com/David-Kunz/jester) `jester`
- [x] [FrenzyExists/aquarium-vim](https://github.com/FrenzyExists/aquarium-vim) `aquarium-vim`
- [x] [JoosepAlviste/nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring) `nvim-ts-context-commentstring`
- [x] [L3MON4D3/LuaSnip](https://github.com/L3MON4D3/LuaSnip) `LuaSnip`
- [x] [LoricAndre/OneTerm.nvim](https://github.com/LoricAndre/OneTerm.nvim) `OneTerm-nvim`
- [x] [Mangeshrex/uwu.vim](https://github.com/Mangeshrex/uwu.vim) `uwu-vim`
- [x] [mcauley-penney/tidy.nvim](https://github.com/mcauley-penney/tidy.nvim) `tidy-nvim`
- [x] [Mofiqul/vscode.nvim](https://github.com/Mofiqul/vscode.nvim) `vscode-nvim`
- [x] [MordechaiHadad/nvim-papadark](https://github.com/MordechaiHadad/nvim-papadark) `nvim-papadark`
    - Moved to [NarutoXY/themer.lua](https://github.com/NarutoXY/themer.lua)
- [x] [NFrid/due.nvim](https://github.com/NFrid/due.nvim) `due-nvim`
- [x] [NTBBloodbath/cheovim](https://github.com/NTBBloodbath/cheovim) `cheovim`
- [x] [NTBBloodbath/doom-one.nvim](https://github.com/NTBBloodbath/doom-one.nvim) `doom-one-nvim`
- [x] [NTBBloodbath/galaxyline.nvim](https://github.com/NTBBloodbath/galaxyline.nvim) `galaxyline-nvim`
- [x] [PHSix/nvim-hybrid](https://github.com/PHSix/nvim-hybrid) `nvim-hybrid`
- [x] [Pocco81/AbbrevMan.nvim](https://github.com/Pocco81/AbbrevMan.nvim) `AbbrevMan-nvim`
- [x] [Pocco81/AutoSave.nvim](https://github.com/Pocco81/AutoSave.nvim) `AutoSave-nvim`
- [x] [Pocco81/DAPInstall.nvim](https://github.com/Pocco81/DAPInstall.nvim) `DAPInstall-nvim`
- [x] [Pocco81/HighStr.nvim](https://github.com/Pocco81/HighStr.nvim) `HighStr-nvim`
- [x] [RRethy/nvim-treesitter-textsubjects](https://github.com/RRethy/nvim-treesitter-textsubjects) `nvim-treesitter-textsubjects`
- [x] [RishabhRD/gruvy](https://github.com/RishabhRD/gruvy) `gruvy`
- [x] [RishabhRD/lspactions](https://github.com/RishabhRD/lspactions) `lspactions`
- [x] [RishabhRD/nvim-rdark](https://github.com/RishabhRD/nvim-rdark) `nvim-rdark`
- [x] [SmiteshP/nvim-gps](https://github.com/SmiteshP/nvim-gps) `nvim-gps`
- [x] [Th3Whit3Wolf/onebuddy](https://github.com/Th3Whit3Wolf/onebuddy) `onebuddy`
- [x] [Th3Whit3Wolf/space-nvim](https://github.com/Th3Whit3Wolf/space-nvim) `space-nvim`
- [x] [ThePrimeagen/vim-be-good](https://github.com/ThePrimeagen/vim-be-good) `vim-be-good`
- [x] [TimUntersberger/neofs](https://github.com/TimUntersberger/neofs) `neofs`
- [x] [Xuyuanp/yanil](https://github.com/Xuyuanp/yanil) `yanil`
- [x] [abecodes/tabout.nvim](https://github.com/abecodes/tabout.nvim) `tabout-nvim`
- [x] [adelarsq/neoline.vim](https://github.com/adelarsq/neoline.vim) `neoline-vim`
- [x] [adisen99/apprentice.nvim](https://github.com/adisen99/apprentice.nvim) `apprentice-nvim`
- [x] [adisen99/codeschool.nvim](https://github.com/adisen99/codeschool.nvim) `codeschool-nvim`
- [x] [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim) `project-nvim`
- [x] [akinsho/dependency-assist.nvim](https://github.com/akinsho/dependency-assist.nvim) `dependency-assist-nvim`
- [x] [akinsho/flutter-tools.nvim](https://github.com/akinsho/flutter-tools.nvim) `flutter-tools-nvim`
- [x] [akinsho/toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) `toggleterm-nvim`
- [x] [alec-gibson/nvim-tetris](https://github.com/alec-gibson/nvim-tetris) `nvim-tetris`
- [x] [alexaandru/nvim-lspupdate](https://github.com/alexaandru/nvim-lspupdate) `nvim-lspupdate`
- [x] [aliou/bats.vim](https://github.com/aliou/bats.vim) `bats-vim`
- [x] [amirrezaask/fuzzy.nvim](https://github.com/amirrezaask/fuzzy.nvim) `fuzzy-nvim`
- [x] [andersevenrud/cmp-tmux](https://github.com/andersevenrud/cmp-tmux) `cmp-tmux`
- [x] [andersevenrud/nordic.nvim](https://github.com/andersevenrud/nordic.nvim) `nordic-nvim`
- [x] [anott03/nvim-lspinstall](https://github.com/anott03/nvim-lspinstall) `nvim-lspinstall`
- [x] [beauwilliams/statusline.lua](https://github.com/beauwilliams/statusline.lua) `statusline-lua`
- [x] [bfredl/nvim-luadev](https://github.com/bfredl/nvim-luadev) `nvim-luadev`
- [x] [bkegley/gloombuddy](https://github.com/bkegley/gloombuddy) `gloombuddy`
- [x] [blackCauldron7/surround.nvim](https://github.com/blackCauldron7/surround.nvim) `surround-nvim`
- [x] [bluz71/vim-moonfly-colors](https://github.com/bluz71/vim-moonfly-colors) `vim-moonfly-colors`
- [x] [bluz71/vim-nightfly-guicolors](https://github.com/bluz71/vim-nightfly-guicolors) `vim-nightfly-guicolors`
- [x] [catppuccin/nvim](https://github.com/catppuccin/nvim) `catppuccin`
- [x] [code-biscuits/nvim-biscuits](https://github.com/code-biscuits/nvim-biscuits) `nvim-biscuits`
- [x] [crispgm/nvim-go](https://github.com/crispgm/nvim-go) `nvim-go`
- [x] [crispgm/nvim-tabline](https://github.com/crispgm/nvim-tabline) `nvim-tabline`
- [x] [crispgm/telescope-heading.nvim](https://github.com/crispgm/telescope-heading.nvim) `telescope-heading-nvim`
- [x] [danymat/neogen](https://github.com/danymat/neogen) `neogen`
- [x] [datwaft/bubbly.nvim](https://github.com/datwaft/bubbly.nvim) `bubbly-nvim`
- [x] [davidgranstrom/scnvim](https://github.com/davidgranstrom/scnvim) `scnvim`
- [x] [dcampos/nvim-snippy](https://github.com/dcampos/nvim-snippy) `nvim-snippy`
- [x] [dkarter/bullets.vim](https://github.com/dkarter/bullets.vim) `bullets-vim`
- [x] [echasnovski/mini.nvim](https://github.com/echasnovski/mini.nvim) `mini-nvim`
- [x] [edolphin-ydf/goimpl.nvim](https://github.com/edolphin-ydf/goimpl.nvim) `goimpl-nvim`
- [x] [ekickx/clipboard-image.nvim](https://github.com/ekickx/clipboard-image.nvim) `clipboard-image-nvim`
- [x] [ellisonleao/glow.nvim](https://github.com/ellisonleao/glow.nvim) `glow-nvim`
- [x] [ethanholz/nvim-lastplace](https://github.com/ethanholz/nvim-lastplace) `nvim-lastplace`
- [x] [feline-nvim/feline.nvim](https://github.com/feline-nvim/feline.nvim) [branch: `develop`] `feline-nvim-develop`
- [x] [filipdutescu/renamer.nvim](https://github.com/filipdutescu/renamer.nvim) `renamer-nvim`
- [x] [folke/lua-dev.nvim](https://github.com/folke/lua-dev.nvim) `lua-dev-nvim`
- [x] [folke/zen-mode.nvim](https://github.com/folke/zen-mode.nvim) `zen-mode-nvim`
- [x] [fuenor/JpFormat.vim](https://github.com/fuenor/JpFormat.vim) `JpFormat-vim`
- [x] [gbprod/cutlass.nvim](https://github.com/gbprod/cutlass.nvim) `cutlass-nvim`
- [x] [gennaro-tedesco/nvim-commaround](https://github.com/gennaro-tedesco/nvim-commaround) `nvim-commaround`
- [x] [glepnir/indent-guides.nvim](https://github.com/glepnir/indent-guides.nvim) `indent-guides-nvim`
- [x] [glepnir/prodoc.nvim](https://github.com/glepnir/prodoc.nvim) `prodoc-nvim`
- [x] [goolord/alpha-nvim](https://github.com/goolord/alpha-nvim) `alpha-nvim`
- [x] [h-hg/fcitx.nvim](https://github.com/h-hg/fcitx.nvim) `fcitx-nvim`
- [x] [henriquehbr/nvim-startup.lua](https://github.com/henriquehbr/nvim-startup.lua) `nvim-startup-lua`
- [x] [houtsnip/vim-emacscommandline](https://github.com/houtsnip/vim-emacscommandline) `vim-emacscommandline`
- [x] [hylang/vim-hy](https://github.com/hylang/vim-hy) `vim-hy`
- [x] [ibhagwan/fzf-lua](https://github.com/ibhagwan/fzf-lua) `fzf-lua`
- [x] [inkch/vim-fish](https://github.com/inkch/vim-fish) `vim-fish-inkch`
- [x] [is0n/fm-nvim](https://github.com/is0n/fm-nvim) `fm-nvim`
- [x] [is0n/jaq-nvim](https://github.com/is0n/jaq-nvim) `jaq-nvim`
- [x] [ishan9299/modus-theme-vim](https://github.com/ishan9299/modus-theme-vim) `modus-theme-vim`
- [x] [jakewvincent/mkdnflow.nvim](https://github.com/jakewvincent/mkdnflow.nvim) `mkdnflow-nvim`
- [x] [jakewvincent/texmagic.nvim](https://github.com/jakewvincent/texmagic.nvim) `texmagic-nvim`
- [x] [jameshiew/nvim-magic](https://github.com/jameshiew/nvim-magic) `nvim-magic`
- [x] [jbyuki/instant.nvim](https://github.com/jbyuki/instant.nvim) `instant-nvim`
- [x] [jbyuki/nabla.nvim](https://github.com/jbyuki/nabla.nvim) `nabla-nvim`
- [x] [jbyuki/one-small-step-for-vimkind](https://github.com/jbyuki/one-small-step-for-vimkind) `one-small-step-for-vimkind`
- [x] [jghauser/auto-pandoc.nvim](https://github.com/jghauser/auto-pandoc.nvim) `auto-pandoc-nvim`
- [x] [jghauser/follow-md-links.nvim](https://github.com/jghauser/follow-md-links.nvim) `follow-md-links-nvim`
- [x] [jghauser/kitty-runner.nvim](https://github.com/jghauser/kitty-runner.nvim) `kitty-runner-nvim`
- [x] [jghauser/mkdir.nvim](https://github.com/jghauser/mkdir.nvim) `mkdir-nvim`
- [x] [jim-at-jibba/ariake-vim-colors](https://github.com/jim-at-jibba/ariake-vim-colors) `ariake-vim-colors`
- [x] [johann2357/nvim-smartbufs](https://github.com/johann2357/nvim-smartbufs) `nvim-smartbufs`
- [x] [jose-elias-alvarez/null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) `null-ls-nvim`
- [x] [jubnzv/virtual-types.nvim](https://github.com/jubnzv/virtual-types.nvim) `virtual-types-nvim`
- [x] [jvgrootveld/telescope-zoxide](https://github.com/jvgrootveld/telescope-zoxide) `telescope-zoxide`
- [x] [kana/vim-textobj-indent](https://github.com/kana/vim-textobj-indent) `vim-textobj-indent`
- [x] [kazhala/close-buffers.nvim](https://github.com/kazhala/close-buffers.nvim) `close-buffers-nvim`
- [x] [kdheepak/monochrome.nvim](https://github.com/kdheepak/monochrome.nvim) `monochrome-nvim`
- [x] [konapun/vacuumline.nvim](https://github.com/konapun/vacuumline.nvim) `vacuumline-nvim`
- [x] [nvim-orgmode/orgmode](https://github.com/nvim-orgmode/orgmode) `orgmode`
- [x] [kvrohit/substrata.nvim](https://github.com/kvrohit/substrata.nvim) `substrata-nvim`
- [x] [kyazdani42/blue-moon](https://github.com/kyazdani42/blue-moon) `blue-moon`
- [x] [ldelossa/calltree.nvim](https://github.com/ldelossa/calltree.nvim) `calltree-nvim`
    - Renamed to [ldelossa/litee.nvim](https://github.com/ldelossa/litee.nvim) `litee-nvim`
- [x] [ldelossa/vimdark](https://github.com/ldelossa/vimdark) `vimdark`
- [x] [lewis6991/spellsitter.nvim](https://github.com/lewis6991/spellsitter.nvim) `spellsitter-nvim`
- [x] [lourenci/github-colors](https://github.com/lourenci/github-colors) `github-colors`
- [x] [lukas-reineke/cmp-rg](https://github.com/lukas-reineke/cmp-rg) `cmp-rg`
- [x] [lukas-reineke/format.nvim](https://github.com/lukas-reineke/format.nvim) `format-nvim`
    - NOTE: deprecated.
- [x] [luukvbaal/nnn.nvim](https://github.com/luukvbaal/nnn.nvim) `nnn-nvim`
- [x] [m00qek/plugin-template.nvim](https://github.com/m00qek/plugin-template.nvim) `plugin-template-nvim`
    - NOTE: This is just a template for neovim plugin.
- [x] [madskjeldgaard/reaper-nvim](https://github.com/madskjeldgaard/reaper-nvim) `reaper-nvim`
- [x] [marko-cerovac/material.nvim](https://github.com/marko-cerovac/material.nvim) `material-nvim`
- [x] [matbme/JABS.nvim](https://github.com/matbme/JABS.nvim) `JABS-nvim`
- [x] [mcchrish/zenbones.nvim](https://github.com/mcchrish/zenbones.nvim) `zenbones-nvim`
- [x] [mfussenegger/nvim-treehopper](https://github.com/mfussenegger/nvim-treehopper) `nvim-treehopper`
- [x] [michaelb/sniprun](https://github.com/michaelb/sniprun) `sniprun`
- [x] [mizlan/iswap.nvim](https://github.com/mizlan/iswap.nvim) `iswap-nvim`
- [x] [mjlbach/babelfish.nvim](https://github.com/mjlbach/babelfish.nvim) `babelfish-nvim`
- [x] [mnacamura/iron.nvim](https://github.com/mnacamura/iron.nvim) `iron-nvim-mnacamura`
- [x] [mnacamura/nvim-srcerite](https://github.com/mnacamura/nvim-srcerite) `nvim-srcerite`
- [x] [mnacamura/vim-fennel-syntax](https://github.com/mnacamura/vim-fennel-syntax) `vim-fennel-syntax`
- [x] [mnacamura/vim-r7rs-syntax](https://github.com/mnacamura/vim-r7rs-syntax) `vim-r7rs-syntax`
- [x] [monaqa/dial.nvim](https://github.com/monaqa/dial.nvim) `dial-nvim`
- [x] [monkoose/matchparen.nvim](https://github.com/monkoose/matchparen.nvim) `matchparen-nvim`
- [x] ~~[ms-jpq/chadtree](https://github.com/ms-jpq/chadtree) `chadtree`~~ Removed as it is officially privided.
- [x] [ms-jpq/coq_nvim](https://github.com/ms-jpq/coq_nvim) `coq-nvim`
- [x] [nanotee/nvim-lsp-basics](https://github.com/nanotee/nvim-lsp-basics) `nvim-lsp-basics`
- [x] [nanotee/sqls.nvim](https://github.com/nanotee/sqls.nvim) `sqls-nvim`
- [x] [navarasu/onedark.nvim](https://github.com/navarasu/onedark.nvim) `onedark-nvim`
- [x] [nekonako/xresources-nvim](https://github.com/nekonako/xresources-nvim) `xresources-nvim`
- [x] [nikvdp/neomux](https://github.com/nikvdp/neomux) `neomux`
- [x] [noib3/nvim-cokeline](https://github.com/noib3/nvim-cokeline) `nvim-cokeline`
- [x] [norcalli/nvim-base16.lua](https://github.com/norcalli/nvim-base16.lua) `nvim-base16-lua`
- [x] [notomo/cmdbuf.nvim](https://github.com/notomo/cmdbuf.nvim) `cmdbuf-nvim`
- [x] [notomo/gesture.nvim](https://github.com/notomo/gesture.nvim) `gesture-nvim`
- [x] [novakne/kosmikoa.nvim](https://github.com/novakne/kosmikoa.nvim) `kosmikoa-nvim`
- [x] [numToStr/Comment.nvim](https://github.com/numToStr/Comment.nvim) `Comment-nvim`
- [x] [nvim-telescope/telescope-bibtex.nvim](https://github.com/nvim-telescope/telescope-bibtex.nvim) `telescope-bibtex-nvim`
- [x] [nxvu699134/vn-night.nvim](https://github.com/nxvu699134/vn-night.nvim) `vn-night-nvim`
- [x] [ojroques/nvim-hardline](https://github.com/ojroques/nvim-hardline) `nvim-hardline`
- [x] [ojroques/nvim-lspfuzzy](https://github.com/ojroques/nvim-lspfuzzy) `nvim-lspfuzzy`
- [x] [petertriho/cmp-git](https://github.com/petertriho/cmp-git) `cmp-git`
- [x] [pianocomposer321/consolation.nvim](https://github.com/pianocomposer321/consolation.nvim) `consolation-nvim`
- [x] [pianocomposer321/yabs.nvim](https://github.com/pianocomposer321/yabs.nvim) `yabs-nvim`
- [x] [projekt0n/github-nvim-theme](https://github.com/projekt0n/github-nvim-theme) `github-nvim-theme`
- [x] [pwntester/codeql.nvim](https://github.com/pwntester/codeql.nvim) `codeql-nvim`
- [x] [pwntester/octo.nvim](https://github.com/pwntester/octo.nvim) `octo-nvim`
- [x] [quangnguyen30192/cmp-nvim-ultisnips](https://github.com/quangnguyen30192/cmp-nvim-ultisnips) `cmp-nvim-ultisnips`
- [x] [rafaelsq/nvim-goc.lua](https://github.com/rafaelsq/nvim-goc.lua) `nvim-goc-lua`
- [x] [rafcamlet/nvim-luapad](https://github.com/rafcamlet/nvim-luapad) `nvim-luapad`
- [x] [rafcamlet/tabline-framework.nvim](https://github.com/rafcamlet/tabline-framework.nvim) `tabline-framework-nvim`
- [x] [raimon49/requirements.txt.vim](https://github.com/raimon49/requirements.txt.vim) `requirements-txt-vim`
- [x] [rhysd/vim-gfm-syntax](https://github.com/rhysd/vim-gfm-syntax) `vim-gfm-syntax`
- [x] [rktjmp/highlight-current-n.nvim](https://github.com/rktjmp/highlight-current-n.nvim) `highlight-current-n-nvim`
- [x] [rktjmp/hotpot.nvim](https://github.com/rktjmp/hotpot.nvim) `hotpot-nvim`
- [x] [rktjmp/paperplanes.nvim](https://github.com/rktjmp/paperplanes.nvim) `paperplanes-nvim`
- [x] [rmehri01/onenord.nvim](https://github.com/rmehri01/onenord.nvim) `onenord-nvim`
- [x] [rockerBOO/boo-colorscheme-nvim](https://github.com/rockerBOO/boo-colorscheme-nvim) `boo-colorscheme-nvim`
- [x] [rose-pine/neovim](https://github.com/rose-pine/neovim) `rose-pine`
- [x] [s1n7ax/nvim-comment-frame](https://github.com/s1n7ax/nvim-comment-frame) `nvim-comment-frame`
- [x] [s1n7ax/nvim-terminal](https://github.com/s1n7ax/nvim-terminal) `nvim-terminal`
- [x] [sQVe/sort.nvim](https://github.com/sQVe/sort.nvim) `sort-nvim`
- [x] [saifulapm/chartoggle.nvim](https://github.com/saifulapm/chartoggle.nvim) `chartoggle-nvim`
- [x] [sainnhe/everforest](https://github.com/sainnhe/everforest) `everforest`
- [x] [savq/melange](https://github.com/savq/melange) `melange`
- [x] [savq/paq-nvim](https://github.com/savq/paq-nvim) `paq-nvim`
- [x] [seandewar/nvimesweeper](https://github.com/seandewar/nvimesweeper) `nvimesweeper`
- [x] [shaeinst/roshnivim-cs](https://github.com/shaeinst/roshnivim-cs) `roshnivim-cs`
- [x] ~~[shaunsingh/moonlight.nvim](https://github.com/shaunsingh/moonlight.nvim) `moonlight-nvim`~~ Removed as it is officially provided.
- [x] [stevearc/dressing.nvim](https://github.com/stevearc/dressing.nvim) `dressing-nvim`
- [x] [stevearc/gkeep.nvim](https://github.com/stevearc/gkeep.nvim) `gkeep-nvim`
- [x] [stevearc/qf_helper.nvim](https://github.com/stevearc/qf_helper.nvim) `qf-helper-nvim`
- [x] [svermeulen/vim-yoink](https://github.com/svermeulen/vim-yoink) `vim-yoink`
- [x] [svermeulen/vimpeccable](https://github.com/svermeulen/vimpeccable) `vimpeccable`
- [x] [tamago324/nlsp-settings.nvim](https://github.com/tamago324/nlsp-settings.nvim) `nlsp-settings-nvim`
- [x] [tami5/lspsaga.nvim](https://github.com/tami5/lspsaga.nvim) `lspsaga-nvim`
- [x] [tamton-aquib/staline.nvim](https://github.com/tamton-aquib/staline.nvim) `staline-nvim`
- [x] [tanvirtin/monokai.nvim](https://github.com/tanvirtin/monokai.nvim) `monokai-nvim`
- [x] [tanvirtin/vgit.nvim](https://github.com/tanvirtin/vgit.nvim) `vgit-nvim`
- [x] [terrortylor/nvim-comment](https://github.com/terrortylor/nvim-comment) `nvim-comment`
- [x] [theniceboy/nvim-deus](https://github.com/theniceboy/nvim-deus) `nvim-deus`
- [x] [tjdevries/astronauta.nvim](https://github.com/tjdevries/astronauta.nvim) `astronauta-nvim`
- [x] [tjdevries/express_line.nvim](https://github.com/tjdevries/express_line.nvim) `express-line-nvim`
- [x] [tjdevries/gruvbuddy.nvim](https://github.com/tjdevries/gruvbuddy.nvim) `gruvbuddy-nvim`
- [x] [tjdevries/vlog.nvim](https://github.com/tjdevries/vlog.nvim) `vlog-nvim`
- [x] [tveskag/nvim-blame-line](https://github.com/tveskag/nvim-blame-line) `nvim-blame-line`
- [x] [nvim-neorg/neorg](https://github.com/nvim-neorg/neorg) `neorg`
- [x] [williamboman/nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) `nvim-lsp-installer`
- [x] [windwp/nvim-projectconfig](https://github.com/windwp/nvim-projectconfig) `nvim-projectconfig`
- [x] [nvim-pack/nvim-spectre](https://github.com/nvim-pack/nvim-spectre) `nvim-spectre`
- [x] [windwp/nvim-ts-autotag](https://github.com/windwp/nvim-ts-autotag) `nvim-ts-autotag`
- [x] [windwp/windline.nvim](https://github.com/windwp/windline.nvim) `windline-nvim`
- [x] [winston0410/commented.nvim](https://github.com/winston0410/commented.nvim) `commented-nvim`
- [x] [xiyaowong/nvim-cursorword](https://github.com/xiyaowong/nvim-cursorword) `nvim-cursorword`
- [x] [xiyaowong/nvim-transparent](https://github.com/xiyaowong/nvim-transparent) `nvim-transparent`
- [x] [yashguptaz/calvera-dark.nvim](https://github.com/yashguptaz/calvera-dark.nvim) `calvera-dark-nvim`
- [x] [yonlu/omni.vim](https://github.com/yonlu/omni.vim) `omni-vim`
- [x] [gitlab:yorickpeterse/nvim-pqf](https://gitlab.com/yorickpeterse/nvim-pqf) `nvim-pqf`

## Another dish!

- [x] [gbprod/substitute.nvim](https://github.com/gbprod/substitute.nvim) `substitute-nvim`
- [x] [startup-nvim/startup.nvim](https://github.com/startup-nvim/startup.nvim) `startup-nvim`
- [x] [Iron-E/nvim-cartographer](https://github.com/Iron-E/nvim-cartographer) `nvim-cartographer`
- [x] [LinArcX/telescope-command-palette.nvim](https://github.com/LinArcX/telescope-command-palette.nvim) `telescope-command-palette-nvim`
- [x] [LionC/nest.nvim](https://github.com/LionC/nest.nvim) `nest-nvim`
- [x] [aserowy/tmux.nvim](https://github.com/aserowy/tmux.nvim)  `tmux-nvim`
- [x] [b0o/mapx.nvim](https://github.com/b0o/mapx.nvim)  `mapx-nvim`
- [x] [beauwilliams/focus.nvim](https://github.com/beauwilliams/focus.nvim) `focus-nvim`: license missing in the upstream
- [x] [chipsenkbeil/distant.nvim](https://github.com/chipsenkbeil/distant.nvim) `distant-nvim`
- [x] [danielpieper/telescope-tmuxinator.nvim](https://github.com/danielpieper/telescope-tmuxinator.nvim)  `telescope-tmuxinator-nvim`
- [x] [henriquehbr/ataraxis.lua](https://github.com/henriquehbr/ataraxis.lua)  `ataraxis-lua`
- [x] [hkupty/nvimux](https://github.com/hkupty/nvimux)  `nvimux`
- [x] [jamestthompson3/nvim-remote-containers](https://github.com/jamestthompson3/nvim-remote-containers)  `nvim-remote-containers`
- [x] [luisiacc/gruvbox-baby](https://github.com/luisiacc/gruvbox-baby)  `gruvbox-baby`
- [x] [numToStr/Navigator.nvim](https://github.com/numToStr/Navigator.nvim)  `Navigator-nvim`
- [x] [sindrets/winshift.nvim](https://github.com/sindrets/winshift.nvim) `winshift-nvim`
- [x] [gitlab:yorickpeterse/nvim-window](https://gitlab.com/yorickpeterse/nvim-window) `nvim-window`

**Comment by m15a** [comment]
Moved some plugins that need not-so-simple overrides to #37.
